parameters:
    twitter_name: 'VotrubaT'
    source_directory: '%kernel.project_dir%/../../../source'
    minimal_gap_in_days: 1 # how many days to wait before publishing another Tweet

    twitter_consumer_key: "..."
    twitter_consumer_secret: "..."
    twitter_oauth_access_token: "..."
    twitter_oauth_access_token_secret: "..."

services:
    _defaults:
        autowire: true
        bind:
            '$siteUrl': '%site_url%'
            '$sourceDirectory': '%source_directory%'
            '$twitterName': '%twitter_name%'
            '$minimalGapInDays': '%minimal_gap_in_days%'

    # PSR-4 autodiscovery
    TomasVotruba\StatieTweetPublisher\:
        resource: ../
        exclude: ../Tweet
        public: true # for container fetch

    # Twitter API
    TomasVotruba\StatieTweetPublisher\TwitterApi\TwitterApiFactory:
        arguments:
            - '%twitter_consumer_key%'
            - '%twitter_consumer_secret%'
            - '%twitter_oauth_access_token%'
            - '%twitter_oauth_access_token_secret%'

    TwitterAPIExchange:
        class: TwitterAPIExchange
        factory: ['@TomasVotruba\StatieTweetPublisher\TwitterApi\TwitterApiFactory', 'create']

    Symfony\Component\Console\Style\SymfonyStyle: ~
